# Generated by Django 3.2.19 on 2023-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(to='page.Page'),
        ),
    ]
