# Generated by Django 3.2.19 on 2023-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('module', '0002_module_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quizzes',
            field=models.ManyToManyField(to='quiz.Quizzes'),
        ),
    ]
